#include "scaffold.hpp"
#include <cstdlib>
#include <fstream>
#include <iostream>

namespace fs = std::filesystem;

namespace scaffold {

namespace {

std::string replace_all(std::string s, const std::string &from, const std::string &to) {
    std::size_t p = 0;
    while ((p = s.find(from, p)) != std::string::npos) {
        s.replace(p, from.size(), to);
        p += to.size();
    }
    return s;
}

bool write_file(const fs::path &p, const std::string &content, std::string &err) {
    std::error_code ec;
    fs::create_directories(p.parent_path(), ec);
    std::ofstream out(p);
    if (!out) {
        err = "cannot write " + p.string();
        return false;
    }
    out << content;
    return true;
}

/* ------------------------------------------------------------------ */
/* Templates. {{NAME}} and {{PORT}} are substituted.                   */
/* ------------------------------------------------------------------ */

const char *kCMake = R"CMAKE(cmake_minimum_required(VERSION 3.16)
project({{NAME}} CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()

find_package(Threads REQUIRED)

# The adapter is a shared library the exchange dlopen()s. It depends only on
# include/ingress/api.h (copied from the MarketSimulator checkout).
add_library({{NAME}} MODULE src/adapter.cpp)
target_include_directories({{NAME}} PRIVATE include src)
target_link_libraries({{NAME}} Threads::Threads)
target_compile_options({{NAME}} PRIVATE -Wall -Wextra)
set_target_properties({{NAME}} PROPERTIES
  PREFIX ""
  LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
if(APPLE)
  set_target_properties({{NAME}} PROPERTIES SUFFIX ".dylib")
endif()
)CMAKE";

const char *kReadme = R"MD(# {{NAME}}

A custom order-entry adapter for the MarketSimulator exchange, generated by
`mktsim up`. It is a shared library the exchange loads at startup. The TCP
serving, client sessions, order-id bookkeeping and report routing are
already written in `src/adapter.cpp`; the wire format is yours, in
`src/protocol.hpp`.

## Build

```
cmake -S . -B build && cmake --build build
```

Produces `build/{{NAME}}.dylib` (macOS) or `build/{{NAME}}.so` (Linux). The
exchange config entry that `mktsim up` wrote points at `build/{{NAME}}`
without the extension, so the same config works on both.

## Run

```
mktsim up <the config mktsim wrote>     # or mktsim up if you saved it as the default
nc localhost {{PORT}}
```

Out of the box the adapter speaks a plain text protocol, one message per
line, so you can try it with `nc` before changing anything:

```
NEW c1 AAPL B 100 10000          # id symbol side qty price [GTC|IOC|FOK]
MARKET c2 AAPL S 50              # id symbol side qty [IOC|FOK]
MODIFY c1 60                     # id new-qty [new-price]
CANCEL c1                        # id
PING
```

and answers

```
ACCEPTED c1 order=72057594037927937 qty=100 px=10000 leaves=100
EXEC c1 order=72057594037927937 qty=50 px=10000 leaves=50 match=3
MODIFIED c1 order=... qty=60 px=10000 leaves=60
CANCELLED c1 order=...
REJECTED c1 symbol_not_found
PONG
ERROR expected NEW, MARKET, CANCEL, MODIFY or PING
```

## Make it yours

Edit `src/protocol.hpp`. Three functions, each with a TODO:

- `frame_end(rx)`: where the first complete message ends in the receive
  buffer. Newline-delimited by default; change it for length-prefixed or
  binary framing.
- `decode(frame)`: turns one inbound frame into an `Inbound` message
  (new / cancel / modify / ping), or `std::nullopt` for garbage.
- `encode(ev)`: turns an `Outbound` event (accepted, rejected, exec,
  cancelled, modified, pong, error) into the bytes to send back.

Everything else stays as generated. Rebuild, then `mktsim down && mktsim up`
to reload the library.

## What the exchange gives you

`include/ingress/api.h` is the contract. One TCP connection is one exchange
session; orders submitted on it report back to it for their whole life.
Reports arrive by polling and the adapter polls after every read, so a
client sees its ack and fills within a millisecond of the match.
)MD";

const char *kProtocol = R"CPP(// {{NAME}}: YOUR wire protocol. Edit this file; leave adapter.cpp alone.
//
// Three hooks:
//   frame_end  - how messages are delimited on the TCP stream
//   decode     - bytes in  -> Inbound (new / cancel / modify / ping)
//   encode     - Outbound  -> bytes out (accepted / rejected / exec / ...)
//
// The defaults speak a plain text protocol, one message per line, so the
// adapter works with `nc` before you change anything. Replace them with
// FIX, your JSON schema, a binary struct, anything.
#pragma once
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <optional>
#include <utility>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace protocol {

/* ---------------- messages the adapter understands ---------------- */

struct Inbound {
    enum Kind { New, Cancel, Modify, Ping } kind = Ping;
    std::string client_id; // your id for the order; echoed on every event
    // New
    std::string symbol;    // ticker as listed in the exchange config
    char side = 'B';       // 'B' or 'S'
    bool market = false;   // market order (price ignored)
    char tif = 'G';        // 'G' GTC, 'I' IOC, 'F' FOK
    std::uint32_t qty = 0;
    std::uint64_t price = 0; // integer price units
    // Modify: qty = new total qty, price = new price or 0 to keep
};

struct Outbound {
    enum Kind { Accepted, Rejected, Exec, Cancelled, Modified, Pong, Error } kind = Pong;
    std::string client_id;
    Outbound() = default;
    explicit Outbound(Kind k, std::string id = "") : kind(k), client_id(std::move(id)) {}
    std::uint64_t order_id = 0;   // the exchange's id, also on the public feed
    std::uint32_t qty = 0;        // Accepted/Modified: order qty. Exec: fill qty
    std::uint64_t price = 0;      // Accepted/Modified: order px. Exec: fill px
    std::uint32_t leaves = 0;     // Accepted/Modified/Exec: resting after the op (Exec 0 = done)
    std::uint64_t match_id = 0;   // Exec
    std::string reason;           // Rejected / Error
};

/* ---------------- 1. framing ---------------- */

// Returns the length of the first complete frame at the start of rx,
// including its delimiter, or 0 if more bytes are needed.
// TODO: change for length-prefixed or binary framing.
inline std::size_t frame_end(const std::string &rx) {
    std::size_t nl = rx.find('\n');
    return nl == std::string::npos ? 0 : nl + 1;
}

/* ---------------- 2. decode ---------------- */

inline std::vector<std::string> split_ws(std::string_view s) {
    std::vector<std::string> out;
    std::string cur;
    for (char c : s) {
        if (c == ' ' || c == '\t' || c == '\r' || c == '\n') {
            if (!cur.empty()) { out.push_back(cur); cur.clear(); }
        } else {
            cur += c;
        }
    }
    if (!cur.empty()) out.push_back(cur);
    return out;
}

// One frame (with its delimiter) -> a message, or nullopt if unparseable.
// TODO: replace with your own format.
inline std::optional<Inbound> decode(std::string_view frame) {
    auto t = split_ws(frame);
    if (t.empty())
        return std::nullopt;
    for (auto &c : t[0]) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    Inbound m;
    auto tif_of = [](const std::string &s) {
        return s == "IOC" ? 'I' : s == "FOK" ? 'F' : 'G';
    };
    if (t[0] == "PING") {
        m.kind = Inbound::Ping;
        return m;
    }
    if ((t[0] == "NEW" && t.size() >= 6) || (t[0] == "MARKET" && t.size() >= 5)) {
        m.kind = Inbound::New;
        m.client_id = t[1];
        m.symbol = t[2];
        m.side = (t[3][0] == 'S' || t[3][0] == 's') ? 'S' : 'B';
        m.qty = static_cast<std::uint32_t>(std::strtoul(t[4].c_str(), nullptr, 10));
        if (t[0] == "NEW") {
            m.price = std::strtoull(t[5].c_str(), nullptr, 10);
            m.tif = t.size() >= 7 ? tif_of(t[6]) : 'G';
        } else {
            m.market = true;
            m.tif = t.size() >= 6 ? tif_of(t[5]) : 'I';
        }
        return m;
    }
    if (t[0] == "CANCEL" && t.size() >= 2) {
        m.kind = Inbound::Cancel;
        m.client_id = t[1];
        return m;
    }
    if (t[0] == "MODIFY" && t.size() >= 3) {
        m.kind = Inbound::Modify;
        m.client_id = t[1];
        m.qty = static_cast<std::uint32_t>(std::strtoul(t[2].c_str(), nullptr, 10));
        m.price = t.size() >= 4 ? std::strtoull(t[3].c_str(), nullptr, 10) : 0;
        return m;
    }
    return std::nullopt;
}

/* ---------------- 3. encode ---------------- */

// An event -> the bytes to send, delimiter included.
// TODO: replace with your own format.
inline std::string encode(const Outbound &e) {
    std::ostringstream o;
    switch (e.kind) {
    case Outbound::Accepted:
        o << "ACCEPTED " << e.client_id << " order=" << e.order_id << " qty=" << e.qty
          << " px=" << e.price << " leaves=" << e.leaves;
        break;
    case Outbound::Rejected:
        o << "REJECTED " << e.client_id << " " << e.reason;
        break;
    case Outbound::Exec:
        o << "EXEC " << e.client_id << " order=" << e.order_id << " qty=" << e.qty
          << " px=" << e.price << " leaves=" << e.leaves << " match=" << e.match_id;
        break;
    case Outbound::Cancelled:
        o << "CANCELLED " << e.client_id << " order=" << e.order_id;
        break;
    case Outbound::Modified:
        o << "MODIFIED " << e.client_id << " order=" << e.order_id << " qty=" << e.qty
          << " px=" << e.price << " leaves=" << e.leaves;
        break;
    case Outbound::Pong:
        o << "PONG";
        break;
    case Outbound::Error:
        o << "ERROR " << e.reason;
        break;
    }
    o << "\n";
    return o.str();
}

} // namespace protocol
)CPP";

const char *kAdapter = R"CPP(// {{NAME}}: generated adapter. You should not need to edit this file.
//
// What it does: listens on TCP, one connection = one exchange session,
// reads frames with protocol::frame_end, decodes them with protocol::decode,
// submits to the exchange, polls reports after every read, and sends them
// back through protocol::encode. Keeps the client-id <-> order-id maps.
//
// Config (from the exchange config's ingress entry): {"port": N, "bind": "0.0.0.0"}
#include "ingress/api.h"
#include "protocol.hpp"
#include <arpa/inet.h>
#include <atomic>
#include <cctype>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <poll.h>
#include <string>
#include <sys/socket.h>
#include <thread>
#include <unistd.h>
#include <unordered_map>
#include <vector>

namespace {

constexpr const char *kAdapterName = "{{NAME}}";

// Tiny JSON field reader for the flat config object.
std::string cfg_str(const std::string &obj, const char *key) {
    std::string k = std::string("\"") + key + "\"";
    std::size_t p = obj.find(k);
    if (p == std::string::npos) return "";
    p = obj.find(':', p + k.size());
    if (p == std::string::npos) return "";
    ++p;
    while (p < obj.size() && (obj[p] == ' ' || obj[p] == '\t')) ++p;
    if (p >= obj.size()) return "";
    if (obj[p] == '"') {
        std::size_t e = obj.find('"', p + 1);
        return e == std::string::npos ? "" : obj.substr(p + 1, e - p - 1);
    }
    std::size_t e = p;
    while (e < obj.size() && (std::isalnum(static_cast<unsigned char>(obj[e])) || obj[e] == '.')) ++e;
    return obj.substr(p, e - p);
}

const char *status_name(uint8_t st) {
    switch (st) {
    case MKTSIM_ST_SYMBOL_NOT_FOUND: return "symbol_not_found";
    case MKTSIM_ST_ORDER_NOT_FOUND: return "order_not_found";
    case MKTSIM_ST_NOT_ENOUGH_LIQUIDITY: return "no_liquidity";
    case MKTSIM_ST_FOK_FAILED: return "fok_unfillable";
    case MKTSIM_ST_INVALID_PRICE: return "invalid_price";
    case MKTSIM_ST_INVALID_QTY: return "invalid_qty";
    case MKTSIM_ST_DUPLICATE: return "duplicate";
    case MKTSIM_ST_OK: return "no_liquidity"; // nothing done
    default: return "failed";
    }
}

struct Conn {
    int fd;
    mktsim_session *session;
    std::string rx, tx;
    std::uint64_t next_req = 1;
    std::unordered_map<std::uint64_t, std::string> pending;  // request_id -> client id
    std::unordered_map<std::uint64_t, std::string> by_order; // order_id -> client id
    std::unordered_map<std::string, std::uint64_t> by_client; // client id -> order_id (0 = pending)
};

struct Adapter {
    const mktsim_exchange_api *api;
    mktsim_exchange *ex;
    std::uint16_t port = {{PORT}};
    std::string bind = "0.0.0.0";
    int listen_fd = -1;
    std::thread thread;
    std::atomic<bool> running{false};
    std::vector<Conn *> conns;

    void log(const std::string &m) { api->log(ex, kAdapterName, m.c_str()); }

    void emit(Conn &c, protocol::Outbound ev) { c.tx += protocol::encode(ev); }

    void reject(Conn &c, const std::string &id, const char *why) {
        protocol::Outbound ev(protocol::Outbound::Rejected, id);
        ev.reason = why;
        emit(c, ev);
    }

    void handle_frame(Conn &c, std::string_view frame) {
        auto m = protocol::decode(frame);
        if (!m) {
            protocol::Outbound ev(protocol::Outbound::Error);
            ev.reason = "expected NEW, MARKET, CANCEL, MODIFY or PING";
            emit(c, ev);
            return;
        }
        switch (m->kind) {
        case protocol::Inbound::Ping:
            emit(c, protocol::Outbound(protocol::Outbound::Pong));
            return;

        case protocol::Inbound::New: {
            if (m->client_id.empty() || m->symbol.empty())
                return reject(c, m->client_id, "bad_request");
            if (c.by_client.count(m->client_id))
                return reject(c, m->client_id, "duplicate");
            uint32_t symbol_id;
            if (api->resolve_symbol(ex, m->symbol.data(), m->symbol.size(), &symbol_id) != MKTSIM_OK)
                return reject(c, m->client_id, "symbol_not_found");
            mktsim_order_req r{};
            r.request_id = c.next_req++;
            r.kind = MKTSIM_REQ_NEW;
            r.side = m->side == 'S' ? MKTSIM_SELL : MKTSIM_BUY;
            r.ord_type = m->market ? MKTSIM_MARKET : MKTSIM_LIMIT;
            r.tif = m->tif == 'I' ? MKTSIM_IOC : m->tif == 'F' ? MKTSIM_FOK : MKTSIM_GTC;
            if (r.ord_type == MKTSIM_MARKET && r.tif == MKTSIM_GTC)
                r.tif = MKTSIM_IOC;
            r.symbol_id = symbol_id;
            r.qty = m->qty;
            r.price = m->price;
            int rc = api->submit(c.session, &r);
            if (rc != MKTSIM_OK)
                return reject(c, m->client_id, rc == MKTSIM_EBUSY ? "busy" : "bad_request");
            c.pending[r.request_id] = m->client_id;
            c.by_client[m->client_id] = 0;
            return;
        }

        case protocol::Inbound::Cancel:
        case protocol::Inbound::Modify: {
            auto it = c.by_client.find(m->client_id);
            if (it == c.by_client.end() || it->second == 0)
                return reject(c, m->client_id, "order_not_found");
            mktsim_order_req r{};
            r.request_id = c.next_req++;
            r.kind = m->kind == protocol::Inbound::Cancel ? MKTSIM_REQ_CANCEL : MKTSIM_REQ_MODIFY;
            r.order_id = it->second;
            if (m->kind == protocol::Inbound::Modify) {
                r.qty = m->qty;
                r.price = m->price;
            }
            int rc = api->submit(c.session, &r);
            if (rc != MKTSIM_OK)
                return reject(c, m->client_id, "busy");
            c.pending[r.request_id] = m->client_id;
            return;
        }
        }
    }

    static void on_report(void *user, const mktsim_report *r) {
        auto &c = *static_cast<Conn *>(user);
        std::string id;
        if (r->request_id) {
            auto p = c.pending.find(r->request_id);
            if (p != c.pending.end()) {
                id = p->second;
                if (r->kind != MKTSIM_RPT_EXECUTION)
                    c.pending.erase(p);
            }
        }
        if (id.empty()) {
            auto b = c.by_order.find(r->order_id);
            if (b != c.by_order.end())
                id = b->second;
        }
        if (id.empty())
            return; // not this connection's order

        protocol::Outbound ev(protocol::Outbound::Error, id);
        ev.order_id = r->order_id;
        switch (r->kind) {
        case MKTSIM_RPT_ACCEPTED:
            c.by_order[r->order_id] = id;
            c.by_client[id] = r->order_id;
            ev.kind = protocol::Outbound::Accepted;
            ev.qty = r->qty; ev.price = r->price; ev.leaves = r->leaves_qty;
            break;
        case MKTSIM_RPT_REJECTED:
            c.by_client.erase(id);
            ev.kind = protocol::Outbound::Rejected;
            ev.reason = status_name(r->status);
            break;
        case MKTSIM_RPT_CANCELLED:
            c.by_client.erase(id);
            c.by_order.erase(r->order_id);
            ev.kind = protocol::Outbound::Cancelled;
            break;
        case MKTSIM_RPT_MODIFIED:
            ev.kind = protocol::Outbound::Modified;
            ev.qty = r->qty; ev.price = r->price; ev.leaves = r->leaves_qty;
            break;
        case MKTSIM_RPT_EXECUTION:
            ev.kind = protocol::Outbound::Exec;
            ev.qty = r->last_qty; ev.price = r->price; ev.match_id = r->match_id;
            ev.leaves = r->leaves_qty;
            if (r->leaves_qty == 0) { // order is done; release the client id
                c.by_client.erase(id);
                c.by_order.erase(r->order_id);
            }
            break;
        default:
            return;
        }
        c.tx += protocol::encode(ev);
    }

    void run() {
        std::vector<pollfd> pfds;
        char buf[16384];
        while (running.load(std::memory_order_relaxed)) {
            pfds.clear();
            pfds.push_back({listen_fd, POLLIN, 0});
            for (auto *c : conns)
                pfds.push_back({c->fd, static_cast<short>(POLLIN | (c->tx.empty() ? 0 : POLLOUT)), 0});
            int n = ::poll(pfds.data(), pfds.size(), 1);
            if (n > 0 && (pfds[0].revents & POLLIN)) {
                for (;;) {
                    int fd = ::accept(listen_fd, nullptr, nullptr);
                    if (fd < 0)
                        break;
                    int one = 1;
                    ::setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
                    ::fcntl(fd, F_SETFL, ::fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
                    auto *c = new Conn{};
                    c->fd = fd;
                    c->session = api->open_session(ex, kAdapterName);
                    conns.push_back(c);
                }
            }
            for (std::size_t i = 0; i < conns.size();) {
                Conn &c = *conns[i];
                bool dead = false;
                short rev = (i + 1 < pfds.size()) ? pfds[i + 1].revents : 0;
                if (rev & (POLLERR | POLLHUP | POLLNVAL))
                    dead = true;
                if (!dead && (rev & POLLIN)) {
                    ssize_t r = ::recv(c.fd, buf, sizeof(buf), 0);
                    if (r <= 0 && !(r < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)))
                        dead = true;
                    else if (r > 0) {
                        c.rx.append(buf, r);
                        std::size_t len;
                        while ((len = protocol::frame_end(c.rx)) != 0) {
                            std::string frame = c.rx.substr(0, len);
                            c.rx.erase(0, len);
                            handle_frame(c, frame);
                        }
                        if (c.rx.size() > (1u << 20))
                            dead = true; // a megabyte without a frame boundary
                    }
                }
                if (!dead) {
                    api->poll(c.session, &Adapter::on_report, &c, 1024);
                    while (!c.tx.empty()) {
                        ssize_t w = ::send(c.fd, c.tx.data(), c.tx.size(), 0);
                        if (w < 0) {
                            if (errno != EAGAIN && errno != EWOULDBLOCK)
                                dead = true;
                            break;
                        }
                        c.tx.erase(0, w);
                    }
                }
                if (dead) {
                    api->close_session(c.session);
                    ::close(c.fd);
                    delete conns[i];
                    conns.erase(conns.begin() + i);
                    pfds.erase(pfds.begin() + i + 1);
                } else {
                    ++i;
                }
            }
        }
        for (auto *c : conns) {
            api->close_session(c->session);
            ::close(c->fd);
            delete c;
        }
        conns.clear();
    }
};

} // namespace

extern "C" {

int mktsim_ingress_init(const mktsim_exchange_api *api, mktsim_exchange *ex, const char *config_json, void **state) {
    if (api->version != MKTSIM_INGRESS_API_VERSION)
        return 1;
    auto *a = new Adapter{};
    a->api = api;
    a->ex = ex;
    std::string cfg = config_json ? config_json : "{}";
    std::string p = cfg_str(cfg, "port");
    if (!p.empty())
        a->port = static_cast<std::uint16_t>(std::strtoul(p.c_str(), nullptr, 10));
    std::string b = cfg_str(cfg, "bind");
    if (!b.empty())
        a->bind = b;
    *state = a;
    return 0;
}

int mktsim_ingress_start(void *state) {
    auto *a = static_cast<Adapter *>(state);
    a->listen_fd = ::socket(AF_INET, SOCK_STREAM, 0);
    if (a->listen_fd < 0)
        return 1;
    int one = 1;
    ::setsockopt(a->listen_fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(a->port);
    if (inet_pton(AF_INET, a->bind.c_str(), &addr.sin_addr) != 1)
        return 1;
    if (::bind(a->listen_fd, reinterpret_cast<sockaddr *>(&addr), sizeof(addr)) < 0 || ::listen(a->listen_fd, 64) < 0) {
        a->log(std::string("bind/listen failed: ") + std::strerror(errno));
        return 1;
    }
    ::fcntl(a->listen_fd, F_SETFL, ::fcntl(a->listen_fd, F_GETFL, 0) | O_NONBLOCK);
    a->running.store(true);
    a->thread = std::thread([a] { a->run(); });
    a->log("listening on " + a->bind + ":" + std::to_string(a->port));
    return 0;
}

void mktsim_ingress_stop(void *state) {
    auto *a = static_cast<Adapter *>(state);
    if (!a->running.exchange(false))
        return;
    if (a->thread.joinable())
        a->thread.join();
    if (a->listen_fd >= 0)
        ::close(a->listen_fd);
    a->listen_fd = -1;
}

void mktsim_ingress_destroy(void *state) { delete static_cast<Adapter *>(state); }

} // extern "C"
)CPP";

const char *kGitignore = "build/\n";

} // namespace

std::string library_path(const Spec &spec) {
    return (spec.dir / "build" / spec.name).string();
}

std::string generate(const Spec &spec) {
    std::error_code ec;
    if (spec.name.empty())
        return "project name is empty";
    for (char c : spec.name)
        if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_'))
            return "project name must be letters, digits and _ only";
    if (fs::exists(spec.dir / "src" / "protocol.hpp", ec))
        return spec.dir.string() + " already contains a scaffolded adapter";

    fs::path api = spec.repo / "gateway" / "include" / "ingress" / "api.h";
    if (!fs::is_regular_file(api, ec))
        return "cannot find the ingress API header at " + api.string();

    auto sub = [&](const char *tpl) {
        return replace_all(replace_all(tpl, "{{NAME}}", spec.name), "{{PORT}}", std::to_string(spec.port));
    };

    std::string err;
    if (!write_file(spec.dir / "CMakeLists.txt", sub(kCMake), err)) return err;
    if (!write_file(spec.dir / "README.md", sub(kReadme), err)) return err;
    if (!write_file(spec.dir / "src" / "protocol.hpp", sub(kProtocol), err)) return err;
    if (!write_file(spec.dir / "src" / "adapter.cpp", sub(kAdapter), err)) return err;
    if (!write_file(spec.dir / ".gitignore", kGitignore, err)) return err;
    fs::create_directories(spec.dir / "include" / "ingress", ec);
    fs::copy_file(api, spec.dir / "include" / "ingress" / "api.h",
                  fs::copy_options::overwrite_existing, ec);
    if (ec)
        return "cannot copy api.h: " + ec.message();
    return "";
}

int build(const Spec &spec) {
    std::string dir = spec.dir.string();
    auto q = [](const std::string &s) { return "'" + s + "'"; };
    std::string cmd = "cmake -S " + q(dir) + " -B " + q(dir + "/build") +
                      " -DCMAKE_BUILD_TYPE=Release >/dev/null && cmake --build " +
                      q(dir + "/build") + " 2>&1 | grep -E 'error|warning|Built target' || true";
    int rc = std::system(cmd.c_str());
    (void)rc;
    // Success is the library existing
    std::error_code ec;
    std::string base = library_path(spec);
    return (fs::exists(base + ".dylib", ec) || fs::exists(base + ".so", ec)) ? 0 : 1;
}

} // namespace scaffold
