#include "scaffold.hpp"
#include <cstdlib>
#include <fstream>
#include <iostream>

namespace fs = std::filesystem;

namespace scaffold {

namespace {

std::string replace_all(std::string s, const std::string &from, const std::string &to) {
    std::size_t p = 0;
    while ((p = s.find(from, p)) != std::string::npos) {
        s.replace(p, from.size(), to);
        p += to.size();
    }
    return s;
}

bool write_file(const fs::path &p, const std::string &content, std::string &err) {
    std::error_code ec;
    fs::create_directories(p.parent_path(), ec);
    std::ofstream out(p);
    if (!out) {
        err = "cannot write " + p.string();
        return false;
    }
    out << content;
    return true;
}

/* ------------------------------------------------------------------ */
/* Templates. {{NAME}} and {{PORT}} are substituted.                   */
/* ------------------------------------------------------------------ */

const char *kCMake = R"CMAKE(cmake_minimum_required(VERSION 3.16)
project({{NAME}} CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()

find_package(Threads REQUIRED)

# The adapter is a shared library the exchange dlopen()s. It depends only on
# include/ingress/api.h (copied from the MarketSimulator checkout).
add_library({{NAME}} MODULE src/adapter.cpp)
target_include_directories({{NAME}} PRIVATE include src)
target_link_libraries({{NAME}} Threads::Threads)
target_compile_options({{NAME}} PRIVATE -Wall -Wextra)
set_target_properties({{NAME}} PROPERTIES
  PREFIX ""
  LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
if(APPLE)
  set_target_properties({{NAME}} PROPERTIES SUFFIX ".dylib")
endif()
)CMAKE";

const char *kReadme = R"MD(# {{NAME}}

A custom order-entry adapter for the MarketSimulator exchange, generated by
`mktsim up`. It is a shared library the exchange loads at startup. The TCP
serving, client sessions, order-id bookkeeping and report routing are
already written in `src/adapter.cpp`; the wire format is yours, in
`src/protocol.hpp`.

## Build

```
cmake -S . -B build && cmake --build build
```

Produces `build/{{NAME}}.dylib` (macOS) or `build/{{NAME}}.so` (Linux). The
exchange config entry that `mktsim up` wrote points at `build/{{NAME}}`
without the extension, so the same config works on both.

## Run

```
mktsim up <the config mktsim wrote>     # or mktsim up if you saved it as the default
nc localhost {{PORT}}
```

Out of the box the adapter speaks a plain text protocol, one message per
line, so you can try it with `nc` before changing anything:

```
NEW c1 AAPL B 100 10000          # id symbol side qty price [GTC|IOC|FOK]
MARKET c2 AAPL S 50              # id symbol side qty [IOC|FOK]
MODIFY c1 60                     # id new-qty [new-price]
CANCEL c1                        # id
PING
```

and answers

```
ACCEPTED c1 order=72057594037927937 qty=100 px=10000 leaves=100
EXEC c1 order=72057594037927937 qty=50 px=10000 leaves=50 match=3
MODIFIED c1 order=... qty=60 px=10000 leaves=60
CANCELLED c1 order=...
REJECTED c1 symbol_not_found
PONG
ERROR expected NEW, MARKET, CANCEL, MODIFY or PING
```

## Make it yours

Edit `src/protocol.hpp`. Three functions, each with a TODO:

- `frame_end(rx)`: where the first complete message ends in the receive
  buffer. Newline-delimited by default; change it for length-prefixed or
  binary framing.
- `decode(frame)`: turns one inbound frame into an `Inbound` message
  (new / cancel / modify / ping), or `std::nullopt` for garbage.
- `encode(ev)`: turns an `Outbound` event (accepted, rejected, exec,
  cancelled, modified, pong, error) into the bytes to send back.

Everything else stays as generated. Rebuild, then `mktsim down && mktsim up`
to reload the library.

## What the exchange gives you

`include/ingress/api.h` is the contract. One TCP connection is one exchange
session; orders submitted on it report back to it for their whole life.
Reports arrive by polling and the adapter polls after every read, so a
client sees its ack and fills within a millisecond of the match.
)MD";

const char *kProtocol = R"CPP(// {{NAME}}: YOUR wire protocol. Edit this file; leave adapter.cpp alone.
//
// Three hooks:
//   frame_end  - how messages are delimited on the TCP stream
//   decode     - bytes in  -> Inbound (new / cancel / modify / ping)
//   encode     - Outbound  -> bytes out (accepted / rejected / exec / ...)
//
// The defaults speak a plain text protocol, one message per line, so the
// adapter works with `nc` before you change anything. Replace them with
// FIX, your JSON schema, a binary struct, anything.
#pragma once
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <optional>
#include <utility>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace protocol {

/* ---------------- messages the adapter understands ---------------- */

struct Inbound {
    enum Kind { New, Cancel, Modify, Ping } kind = Ping;
    std::string client_id; // your id for the order; echoed on every event
    // New
    std::string symbol;    // ticker as listed in the exchange config
    char side = 'B';       // 'B' or 'S'
    bool market = false;   // market order (price ignored)
    char tif = 'G';        // 'G' GTC, 'I' IOC, 'F' FOK
    std::uint32_t qty = 0;
    std::uint64_t price = 0; // integer price units
    // Modify: qty = new total qty, price = new price or 0 to keep
};

struct Outbound {
    enum Kind { Accepted, Rejected, Exec, Cancelled, Modified, Pong, Error } kind = Pong;
    std::string client_id;
    Outbound() = default;
    explicit Outbound(Kind k, std::string id = "") : kind(k), client_id(std::move(id)) {}
    std::uint64_t order_id = 0;   // the exchange's id, also on the public feed
    std::uint32_t qty = 0;        // Accepted/Modified: order qty. Exec: fill qty
    std::uint64_t price = 0;      // Accepted/Modified: order px. Exec: fill px
    std::uint32_t leaves = 0;     // Accepted/Modified/Exec: resting after the op (Exec 0 = done)
    std::uint64_t match_id = 0;   // Exec
    std::string reason;           // Rejected / Error
};

/* ---------------- 1. framing ---------------- */

// Returns the length of the first complete frame at the start of rx,
// including its delimiter, or 0 if more bytes are needed.
// TODO: change for length-prefixed or binary framing.
inline std::size_t frame_end(const std::string &rx) {
    std::size_t nl = rx.find('\n');
    return nl == std::string::npos ? 0 : nl + 1;
}

/* ---------------- 2. decode ---------------- */

inline std::vector<std::string> split_ws(std::string_view s) {
    std::vector<std::string> out;
    std::string cur;
    for (char c : s) {
        if (c == ' ' || c == '\t' || c == '\r' || c == '\n') {
            if (!cur.empty()) { out.push_back(cur); cur.clear(); }
        } else {
            cur += c;
        }
    }
    if (!cur.empty()) out.push_back(cur);
    return out;
}

// One frame (with its delimiter) -> a message, or nullopt if unparseable.
// TODO: replace with your own format.
inline std::optional<Inbound> decode(std::string_view frame) {
    auto t = split_ws(frame);
    if (t.empty())
        return std::nullopt;
    for (auto &c : t[0]) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    Inbound m;
    auto tif_of = [](const std::string &s) {
        return s == "IOC" ? 'I' : s == "FOK" ? 'F' : 'G';
    };
    if (t[0] == "PING") {
        m.kind = Inbound::Ping;
        return m;
    }
    if ((t[0] == "NEW" && t.size() >= 6) || (t[0] == "MARKET" && t.size() >= 5)) {
        m.kind = Inbound::New;
        m.client_id = t[1];
        m.symbol = t[2];
        m.side = (t[3][0] == 'S' || t[3][0] == 's') ? 'S' : 'B';
        m.qty = static_cast<std::uint32_t>(std::strtoul(t[4].c_str(), nullptr, 10));
        if (t[0] == "NEW") {
            m.price = std::strtoull(t[5].c_str(), nullptr, 10);
            m.tif = t.size() >= 7 ? tif_of(t[6]) : 'G';
        } else {
            m.market = true;
            m.tif = t.size() >= 6 ? tif_of(t[5]) : 'I';
        }
        return m;
    }
    if (t[0] == "CANCEL" && t.size() >= 2) {
        m.kind = Inbound::Cancel;
        m.client_id = t[1];
        return m;
    }
    if (t[0] == "MODIFY" && t.size() >= 3) {
        m.kind = Inbound::Modify;
        m.client_id = t[1];
        m.qty = static_cast<std::uint32_t>(std::strtoul(t[2].c_str(), nullptr, 10));
        m.price = t.size() >= 4 ? std::strtoull(t[3].c_str(), nullptr, 10) : 0;
        return m;
    }
    return std::nullopt;
}

/* ---------------- 3. encode ---------------- */

// An event -> the bytes to send, delimiter included.
// TODO: replace with your own format.
inline std::string encode(const Outbound &e) {
    std::ostringstream o;
    switch (e.kind) {
    case Outbound::Accepted:
        o << "ACCEPTED " << e.client_id << " order=" << e.order_id << " qty=" << e.qty
          << " px=" << e.price << " leaves=" << e.leaves;
        break;
    case Outbound::Rejected:
        o << "REJECTED " << e.client_id << " " << e.reason;
        break;
    case Outbound::Exec:
        o << "EXEC " << e.client_id << " order=" << e.order_id << " qty=" << e.qty
          << " px=" << e.price << " leaves=" << e.leaves << " match=" << e.match_id;
        break;
    case Outbound::Cancelled:
        o << "CANCELLED " << e.client_id << " order=" << e.order_id;
        break;
    case Outbound::Modified:
        o << "MODIFIED " << e.client_id << " order=" << e.order_id << " qty=" << e.qty
          << " px=" << e.price << " leaves=" << e.leaves;
        break;
    case Outbound::Pong:
        o << "PONG";
        break;
    case Outbound::Error:
        o << "ERROR " << e.reason;
        break;
    }
    o << "\n";
    return o.str();
}

} // namespace protocol
)CPP";

const char *kAdapter = R"CPP(// {{NAME}}: generated adapter. You should not need to edit this file.
//
// What it does: listens on TCP, one connection = one exchange session,
// reads frames with protocol::frame_end, decodes them with protocol::decode,
// submits to the exchange, polls reports after every read, and sends them
// back through protocol::encode. Keeps the client-id <-> order-id maps.
//
// Config (from the exchange config's ingress entry): {"port": N, "bind": "0.0.0.0"}
#include "ingress/api.h"
#include "protocol.hpp"
#include <arpa/inet.h>
#include <atomic>
#include <cctype>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <poll.h>
#include <string>
#include <sys/socket.h>
#include <thread>
#include <unistd.h>
#include <unordered_map>
#include <vector>

namespace {

constexpr const char *kAdapterName = "{{NAME}}";

// Tiny JSON field reader for the flat config object.
std::string cfg_str(const std::string &obj, const char *key) {
    std::string k = std::string("\"") + key + "\"";
    std::size_t p = obj.find(k);
    if (p == std::string::npos) return "";
    p = obj.find(':', p + k.size());
    if (p == std::string::npos) return "";
    ++p;
    while (p < obj.size() && (obj[p] == ' ' || obj[p] == '\t')) ++p;
    if (p >= obj.size()) return "";
    if (obj[p] == '"') {
        std::size_t e = obj.find('"', p + 1);
        return e == std::string::npos ? "" : obj.substr(p + 1, e - p - 1);
    }
    std::size_t e = p;
    while (e < obj.size() && (std::isalnum(static_cast<unsigned char>(obj[e])) || obj[e] == '.')) ++e;
    return obj.substr(p, e - p);
}

const char *status_name(uint8_t st) {
    switch (st) {
    case MKTSIM_ST_SYMBOL_NOT_FOUND: return "symbol_not_found";
    case MKTSIM_ST_ORDER_NOT_FOUND: return "order_not_found";
    case MKTSIM_ST_NOT_ENOUGH_LIQUIDITY: return "no_liquidity";
    case MKTSIM_ST_FOK_FAILED: return "fok_unfillable";
    case MKTSIM_ST_INVALID_PRICE: return "invalid_price";
    case MKTSIM_ST_INVALID_QTY: return "invalid_qty";
    case MKTSIM_ST_DUPLICATE: return "duplicate";
    case MKTSIM_ST_OK: return "no_liquidity"; // nothing done
    default: return "failed";
    }
}

struct Conn {
    int fd;
    mktsim_session *session;
    std::string rx, tx;
    std::uint64_t next_req = 1;
    std::unordered_map<std::uint64_t, std::string> pending;  // request_id -> client id
    std::unordered_map<std::uint64_t, std::string> by_order; // order_id -> client id
    std::unordered_map<std::string, std::uint64_t> by_client; // client id -> order_id (0 = pending)
};

struct Adapter {
    const mktsim_exchange_api *api;
    mktsim_exchange *ex;
    std::uint16_t port = {{PORT}};
    std::string bind = "0.0.0.0";
    int listen_fd = -1;
    std::thread thread;
    std::atomic<bool> running{false};
    std::vector<Conn *> conns;

    void log(const std::string &m) { api->log(ex, kAdapterName, m.c_str()); }

    void emit(Conn &c, protocol::Outbound ev) { c.tx += protocol::encode(ev); }

    void reject(Conn &c, const std::string &id, const char *why) {
        protocol::Outbound ev(protocol::Outbound::Rejected, id);
        ev.reason = why;
        emit(c, ev);
    }

    void handle_frame(Conn &c, std::string_view frame) {
        auto m = protocol::decode(frame);
        if (!m) {
            protocol::Outbound ev(protocol::Outbound::Error);
            ev.reason = "expected NEW, MARKET, CANCEL, MODIFY or PING";
            emit(c, ev);
            return;
        }
        switch (m->kind) {
        case protocol::Inbound::Ping:
            emit(c, protocol::Outbound(protocol::Outbound::Pong));
            return;

        case protocol::Inbound::New: {
            if (m->client_id.empty() || m->symbol.empty())
                return reject(c, m->client_id, "bad_request");
            if (c.by_client.count(m->client_id))
                return reject(c, m->client_id, "duplicate");
            uint32_t symbol_id;
            if (api->resolve_symbol(ex, m->symbol.data(), m->symbol.size(), &symbol_id) != MKTSIM_OK)
                return reject(c, m->client_id, "symbol_not_found");
            mktsim_order_req r{};
            r.request_id = c.next_req++;
            r.kind = MKTSIM_REQ_NEW;
            r.side = m->side == 'S' ? MKTSIM_SELL : MKTSIM_BUY;
            r.ord_type = m->market ? MKTSIM_MARKET : MKTSIM_LIMIT;
            r.tif = m->tif == 'I' ? MKTSIM_IOC : m->tif == 'F' ? MKTSIM_FOK : MKTSIM_GTC;
            if (r.ord_type == MKTSIM_MARKET && r.tif == MKTSIM_GTC)
                r.tif = MKTSIM_IOC;
            r.symbol_id = symbol_id;
            r.qty = m->qty;
            r.price = m->price;
            int rc = api->submit(c.session, &r);
            if (rc != MKTSIM_OK)
                return reject(c, m->client_id, rc == MKTSIM_EBUSY ? "busy" : "bad_request");
            c.pending[r.request_id] = m->client_id;
            c.by_client[m->client_id] = 0;
            return;
        }

        case protocol::Inbound::Cancel:
        case protocol::Inbound::Modify: {
            auto it = c.by_client.find(m->client_id);
            if (it == c.by_client.end() || it->second == 0)
                return reject(c, m->client_id, "order_not_found");
            mktsim_order_req r{};
            r.request_id = c.next_req++;
            r.kind = m->kind == protocol::Inbound::Cancel ? MKTSIM_REQ_CANCEL : MKTSIM_REQ_MODIFY;
            r.order_id = it->second;
            if (m->kind == protocol::Inbound::Modify) {
                r.qty = m->qty;
                r.price = m->price;
            }
            int rc = api->submit(c.session, &r);
            if (rc != MKTSIM_OK)
                return reject(c, m->client_id, "busy");
            c.pending[r.request_id] = m->client_id;
            return;
        }
        }
    }

    static void on_report(void *user, const mktsim_report *r) {
        auto &c = *static_cast<Conn *>(user);
        std::string id;
        if (r->request_id) {
            auto p = c.pending.find(r->request_id);
            if (p != c.pending.end()) {
                id = p->second;
                if (r->kind != MKTSIM_RPT_EXECUTION)
                    c.pending.erase(p);
            }
        }
        if (id.empty()) {
            auto b = c.by_order.find(r->order_id);
            if (b != c.by_order.end())
                id = b->second;
        }
        if (id.empty())
            return; // not this connection's order

        protocol::Outbound ev(protocol::Outbound::Error, id);
        ev.order_id = r->order_id;
        switch (r->kind) {
        case MKTSIM_RPT_ACCEPTED:
            c.by_order[r->order_id] = id;
            c.by_client[id] = r->order_id;
            ev.kind = protocol::Outbound::Accepted;
            ev.qty = r->qty; ev.price = r->price; ev.leaves = r->leaves_qty;
            break;
        case MKTSIM_RPT_REJECTED:
            c.by_client.erase(id);
            ev.kind = protocol::Outbound::Rejected;
            ev.reason = status_name(r->status);
            break;
        case MKTSIM_RPT_CANCELLED:
            c.by_client.erase(id);
            c.by_order.erase(r->order_id);
            ev.kind = protocol::Outbound::Cancelled;
            break;
        case MKTSIM_RPT_MODIFIED:
            ev.kind = protocol::Outbound::Modified;
            ev.qty = r->qty; ev.price = r->price; ev.leaves = r->leaves_qty;
            break;
        case MKTSIM_RPT_EXECUTION:
            ev.kind = protocol::Outbound::Exec;
            ev.qty = r->last_qty; ev.price = r->price; ev.match_id = r->match_id;
            ev.leaves = r->leaves_qty;
            if (r->leaves_qty == 0) { // order is done; release the client id
                c.by_client.erase(id);
                c.by_order.erase(r->order_id);
            }
            break;
        default:
            return;
        }
        c.tx += protocol::encode(ev);
    }

    void run() {
        std::vector<pollfd> pfds;
        char buf[16384];
        while (running.load(std::memory_order_relaxed)) {
            pfds.clear();
            pfds.push_back({listen_fd, POLLIN, 0});
            for (auto *c : conns)
                pfds.push_back({c->fd, static_cast<short>(POLLIN | (c->tx.empty() ? 0 : POLLOUT)), 0});
            int n = ::poll(pfds.data(), pfds.size(), 1);
            if (n > 0 && (pfds[0].revents & POLLIN)) {
                for (;;) {
                    int fd = ::accept(listen_fd, nullptr, nullptr);
                    if (fd < 0)
                        break;
                    int one = 1;
                    ::setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
                    ::fcntl(fd, F_SETFL, ::fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
                    auto *c = new Conn{};
                    c->fd = fd;
                    c->session = api->open_session(ex, kAdapterName);
                    conns.push_back(c);
                }
            }
            for (std::size_t i = 0; i < conns.size();) {
                Conn &c = *conns[i];
                bool dead = false;
                short rev = (i + 1 < pfds.size()) ? pfds[i + 1].revents : 0;
                if (rev & (POLLERR | POLLHUP | POLLNVAL))
                    dead = true;
                if (!dead && (rev & POLLIN)) {
                    ssize_t r = ::recv(c.fd, buf, sizeof(buf), 0);
                    if (r <= 0 && !(r < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)))
                        dead = true;
                    else if (r > 0) {
                        c.rx.append(buf, r);
                        std::size_t len;
                        while ((len = protocol::frame_end(c.rx)) != 0) {
                            std::string frame = c.rx.substr(0, len);
                            c.rx.erase(0, len);
                            handle_frame(c, frame);
                        }
                        if (c.rx.size() > (1u << 20))
                            dead = true; // a megabyte without a frame boundary
                    }
                }
                if (!dead) {
                    api->poll(c.session, &Adapter::on_report, &c, 1024);
                    while (!c.tx.empty()) {
                        ssize_t w = ::send(c.fd, c.tx.data(), c.tx.size(), 0);
                        if (w < 0) {
                            if (errno != EAGAIN && errno != EWOULDBLOCK)
                                dead = true;
                            break;
                        }
                        c.tx.erase(0, w);
                    }
                }
                if (dead) {
                    api->close_session(c.session);
                    ::close(c.fd);
                    delete conns[i];
                    conns.erase(conns.begin() + i);
                    pfds.erase(pfds.begin() + i + 1);
                } else {
                    ++i;
                }
            }
        }
        for (auto *c : conns) {
            api->close_session(c->session);
            ::close(c->fd);
            delete c;
        }
        conns.clear();
    }
};

} // namespace

extern "C" {

int mktsim_ingress_init(const mktsim_exchange_api *api, mktsim_exchange *ex, const char *config_json, void **state) {
    if (api->version != MKTSIM_INGRESS_API_VERSION)
        return 1;
    auto *a = new Adapter{};
    a->api = api;
    a->ex = ex;
    std::string cfg = config_json ? config_json : "{}";
    std::string p = cfg_str(cfg, "port");
    if (!p.empty())
        a->port = static_cast<std::uint16_t>(std::strtoul(p.c_str(), nullptr, 10));
    std::string b = cfg_str(cfg, "bind");
    if (!b.empty())
        a->bind = b;
    *state = a;
    return 0;
}

int mktsim_ingress_start(void *state) {
    auto *a = static_cast<Adapter *>(state);
    a->listen_fd = ::socket(AF_INET, SOCK_STREAM, 0);
    if (a->listen_fd < 0)
        return 1;
    int one = 1;
    ::setsockopt(a->listen_fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(a->port);
    if (inet_pton(AF_INET, a->bind.c_str(), &addr.sin_addr) != 1)
        return 1;
    if (::bind(a->listen_fd, reinterpret_cast<sockaddr *>(&addr), sizeof(addr)) < 0 || ::listen(a->listen_fd, 64) < 0) {
        a->log(std::string("bind/listen failed: ") + std::strerror(errno));
        return 1;
    }
    ::fcntl(a->listen_fd, F_SETFL, ::fcntl(a->listen_fd, F_GETFL, 0) | O_NONBLOCK);
    a->running.store(true);
    a->thread = std::thread([a] { a->run(); });
    a->log("listening on " + a->bind + ":" + std::to_string(a->port));
    return 0;
}

void mktsim_ingress_stop(void *state) {
    auto *a = static_cast<Adapter *>(state);
    if (!a->running.exchange(false))
        return;
    if (a->thread.joinable())
        a->thread.join();
    if (a->listen_fd >= 0)
        ::close(a->listen_fd);
    a->listen_fd = -1;
}

void mktsim_ingress_destroy(void *state) { delete static_cast<Adapter *>(state); }

} // extern "C"
)CPP";

const char *kGitignore = "build/\n";

const char *kPyReadme = R"MD(# {{NAME}}

Python order flow for the MarketSimulator exchange, generated by `mktsim up`.

```
python3 {{MAIN}}            # with the exchange running (mktsim up)
mktsim tui                  # watch the books
```

`mktsim/` is the client library (copied from the exchange repo's `python/mktsim`):

- `Strategy`: subclass it; hooks `on_start`, `on_report(r)`, `on_tick`, `on_trade(t)`, `on_stop`.
  State on `self`; `self.ex` is your exchange session, `self.world` the shared view.
- `Exchange` (self.ex): `buy(sym, qty, price=None, tif="GTC")`, `sell`, `cancel(id)`,
  `modify(id, qty, price=None)`, `cancel_all(sym=None)`, `orders(sym, side)`,
  `has_side`, `open` (live orders), `position` (per symbol), `cash`, `pnl(marks)`.
- `World` (self.world): `now()`, `book(sym)`, `mid(sym)`, `marks()`, `fundamental[sym]`,
  `at(seconds, fn)`, `shock(seconds, sym, delta)`.
- `Feed`: subscribes to the public multicast feed, bootstraps from the snapshot
  server, keeps an L3 `Book` per symbol: `best_bid()`, `best_ask()`, `mid()`,
  `spread()`, `depth(side, levels)`, `last`, `volume`.
- `run(strategy)` runs one; `run_many([...])` runs a population in one process,
  each agent on its own session, one event loop, shared World.
- `agents`: `NoiseTrader` (Hawkes arrivals), `MarketMaker`, `MomentumTaker`,
  `InformedTrader`, and `population(symbols, noise=, makers=, momentum=, informed=)`.
- `Hawkes(mu, alpha, beta)`: self-exciting arrivals for your own agents.

Rebuild nothing: edit, rerun. Report fields: `kind` (accepted, rejected, exec,
cancelled, modified), `id`, `side`, `sym`, `order`, `qty`, `px`, `leaves`,
`match`, `reason`.
)MD";

// The Python client is copied from <repo>/python/mktsim (see generate_python).

const char *kPyStrategy = R"PY("""{{NAME}}: your trading strategy against the simulated market.

Run with the exchange up:   python3 strategy.py
Watch the book:             mktsim tui

A strategy is a class with hooks; keep your state on self. self.ex is your
exchange session, self.world the shared market view (public books from the
feed, the clock). The example is a market maker that quotes around the
public mid and leans against inventory. Replace it with your own.
"""
from mktsim import Report, Strategy, run


class MyStrategy(Strategy):
    tick_ms = 100

    def __init__(self, symbol="AAPL", size=100, half_spread=5, lean=0.02):
        self.symbol, self.size, self.half_spread, self.lean = symbol, size, half_spread, lean

    def on_start(self):
        print(f"trading {self.symbol}")

    def on_report(self, r: Report):
        if r.kind == "exec":
            pos = self.ex.position.get(self.symbol, 0)
            print(f"FILL {r.side} {r.qty} @ {r.px}  position={pos:+d}  pnl={self.pnl():+d}")
        elif r.kind == "rejected":
            print(f"rejected {r.id}: {r.reason}")

    def on_tick(self):
        mid = self.mid(self.symbol)          # public mid from the feed
        if mid is None:
            return                           # no market yet
        pos = self.ex.position.get(self.symbol, 0)
        fair = int(mid - self.lean * pos)    # long -> quote lower
        want = {"B": fair - self.half_spread, "S": fair + self.half_spread}
        for o in self.ex.orders(self.symbol):
            if o.px != want[o.side]:
                self.ex.modify(o.id, o.qty, want[o.side])
            want[o.side] = None
        if want["B"] is not None:
            self.ex.buy(self.symbol, self.size, want["B"])
        if want["S"] is not None:
            self.ex.sell(self.symbol, self.size, want["S"])

    def on_stop(self):
        self.ex.cancel_all()
        print(f"final pnl {self.pnl():+d}, position {self.ex.position}")


if __name__ == "__main__":
    run(MyStrategy(), port={{PORT}}, feed={{FEED}})
)PY";

const char *kPyMarket = R"PY("""{{NAME}}: a simulated market. Your agents ARE the order flow.

Run with the exchange up (demo flow off):   python3 market.py [--workers 4]
Watch it:                                   mktsim tui
Let traders attach:                         they connect to the same exchange

A Scenario is a seeded, reproducible market: the population, how the
latent fundamental moves, and what shocks happen when. Start from one of
the predefined ones (python3 -m mktsim.market list) or build your own below.
Every agent is its own exchange session with the private World
(self.world.fundamental) plus the public books (self.mid(sym)).
"""
import sys

from mktsim import Feed, Scenario, Strategy, agents
from mktsim.sim import SCENARIOS


class Arbitrageur(Strategy):
    """Your own agent: fades large deviations from the fundamental."""
    tick_ms = 200

    def __init__(self, sym, edge=8, clip=30):
        self.sym, self.edge, self.clip = sym, edge, clip

    def on_tick(self):
        m, v = self.mid(self.sym), self.world.fundamental[self.sym]
        if m is None:
            return
        if m > v + self.edge:
            self.ex.sell(self.sym, self.clip, m - 1, tif="IOC")
        elif m < v - self.edge:
            self.ex.buy(self.sym, self.clip, m + 1, tif="IOC")


def population(symbols, seed):
    """The agents. Mix the library's with your own."""
    pop = agents.population(symbols, noise=8, makers=1, momentum=1, informed=1, seed=seed,
                            noise_rate=1.0, noise_cluster=0.5)
    pop += [Arbitrageur(s) for s in symbols]
    return pop


SCENARIO = Scenario(
    name="{{NAME}}",
    description="my market",
    population=population,
    fundamental={"vol": 0.8, "revert": 0.01},        # Fundamental() kwargs: vol, drift, revert
    shocks=[(30.0, "AAPL", +60)],                      # (seconds, symbol, delta)
    symbols=["AAPL", "MSFT", "GOOG"],
    seed=7,
)

if __name__ == "__main__":
    workers = int(sys.argv[sys.argv.index("--workers") + 1]) if "--workers" in sys.argv else 1
    feed = Feed(group="{{GROUP}}", port={{FEEDPORT}}, snapshot_port={{SNAPPORT}})
    SCENARIO.run(port={{PORT}}, feed=feed, workers=workers, report_every=5)
)PY";

/* ---------------- C++ flow-model plugin: in-process load generation ---------------- */

const char *kFlowCMake = R"CMAKE(cmake_minimum_required(VERSION 3.16)
project({{NAME}} CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()
find_package(Threads REQUIRED)
add_library({{NAME}} MODULE src/flow_adapter.cpp)
target_include_directories({{NAME}} PRIVATE include src)
target_link_libraries({{NAME}} Threads::Threads)
target_compile_options({{NAME}} PRIVATE -Wall -Wextra -O2)
set_target_properties({{NAME}} PROPERTIES PREFIX "" LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
if(APPLE)
  set_target_properties({{NAME}} PROPERTIES SUFFIX ".dylib")
endif()
)CMAKE";

const char *kFlowReadme = R"MD(# {{NAME}}

An in-process order-flow model for the MarketSimulator exchange, generated
by `mktsim up`. The exchange loads it as an ingress plugin and runs it on
its own thread with direct access to the matching engine's order entry,
so it can drive tens of thousands of orders a second with no sockets in
the way. Use it when a Python population is not fast enough.

## Build and run

```
cmake -S . -B build && cmake --build build
mktsim down && mktsim up        # the config already points at build/{{NAME}}
```

## Your model: `src/model.hpp`

`src/flow_adapter.cpp` (generated, leave it) opens `sessions` exchange
sessions, paces calls to your model at `rate` orders per second, submits
what it returns, and delivers every report back to it. You write:

- `Model(const Context&)`: symbols, session count, seed, config JSON.
- `bool next(uint64_t now_ns, Order &out)`: fill in `out` (session, kind
  NEW/CANCEL/MODIFY, symbol, side, type, tif, qty, price or order_id) and
  return true to submit it; false to skip this slot.
- `void on_report(int session, const mktsim_report &r)`: acks, fills,
  cancels for that session's orders. Track what you need.
- `double rate() const`: target orders per second (the adapter paces to it).

The default model is a Hawkes-style flow: each symbol's mid follows a
random walk, arrivals cluster after recent activity, limits scatter
around the mid, some orders cross, resting orders are cancelled after a
while. Replace it with your own process.

Config keys from the exchange config's ingress entry: `sessions` (default
{{SESSIONS}}), `rate` (default {{RATE}}), `seed`, plus anything you read in Model().
)MD";

const char *kFlowModel = R"CPP(// {{NAME}}: YOUR order-flow model. Edit this file; leave flow_adapter.cpp alone.
//
// The adapter calls next() at `rate()` orders per second from one thread and
// hands every report to on_report(). Keep state on the Model.
#pragma once
#include "ingress/api.h"
#include <cmath>
#include <cstdint>
#include <random>
#include <string>
#include <vector>

struct Context {
    std::vector<mktsim_symbol_info> symbols; // ticker + symbol_id
    int sessions;                            // sessions the adapter opened
    std::uint64_t seed;
    std::string config_json;                 // this plugin's config object
};

struct Order {
    int session = 0;
    std::uint8_t kind = MKTSIM_REQ_NEW;       // MKTSIM_REQ_NEW / CANCEL / MODIFY
    std::uint32_t symbol_id = 0;
    std::uint8_t side = MKTSIM_BUY;
    std::uint8_t ord_type = MKTSIM_LIMIT;
    std::uint8_t tif = MKTSIM_GTC;
    std::uint32_t qty = 0;
    std::uint64_t price = 0;
    std::uint64_t order_id = 0;               // CANCEL / MODIFY
};

class Model {
  public:
    explicit Model(const Context &ctx)
        : ctx_(ctx), rng_(ctx.seed ? ctx.seed : 1), mid_(ctx.symbols.size(), 10000.0),
          excess_(0.0), last_ns_(0) {
        live_.resize(ctx.sessions);
    }

    double rate() const { return {{RATE}}.0; }   // orders per second, all sessions

    // One decision. Return true and fill `out` to submit an order.
    bool next(std::uint64_t now_ns, Order &out) {
        if (ctx_.symbols.empty())
            return false;
        // Self-excitation: recent activity raises the chance this slot is used
        double dt = last_ns_ ? (now_ns - last_ns_) / 1e9 : 1.0;
        last_ns_ = now_ns;
        excess_ *= std::exp(-2.0 * dt);
        double p_act = std::min(1.0, 0.6 + excess_);
        if (uni_(rng_) > p_act)
            return false;
        excess_ = std::min(excess_ + 0.05, 0.4);

        int s = static_cast<int>(rng_() % ctx_.symbols.size());
        std::uint32_t sym = ctx_.symbols[s].symbol_id;
        mid_[s] += gauss_(rng_) * 0.3;               // random-walk fair value
        int session = static_cast<int>(rng_() % ctx_.sessions);
        auto &mine = live_[session];

        out = Order{};
        out.session = session;
        out.symbol_id = sym;
        double u = uni_(rng_);
        if (u < 0.25 && !mine.empty()) {             // cancel something resting
            std::size_t k = rng_() % mine.size();
            out.kind = MKTSIM_REQ_CANCEL;
            out.order_id = mine[k];
            mine[k] = mine.back();
            mine.pop_back();
            return true;
        }
        out.kind = MKTSIM_REQ_NEW;
        out.side = (rng_() & 1) ? MKTSIM_BUY : MKTSIM_SELL;
        out.qty = 1 + static_cast<std::uint32_t>(rng_() % 200);
        if (u < 0.40) {                              // aggressive: cross the spread
            out.tif = MKTSIM_IOC;
            out.price = static_cast<std::uint64_t>(mid_[s] + (out.side == MKTSIM_BUY ? 20 : -20));
        } else {                                     // passive: rest near the mid
            double off = 1 + rng_() % 15;
            out.price = static_cast<std::uint64_t>(mid_[s] + (out.side == MKTSIM_BUY ? -off : off));
        }
        if (out.price < 1) out.price = 1;
        return true;
    }

    void on_report(int session, const mktsim_report &r) {
        auto &mine = live_[session];
        if (r.kind == MKTSIM_RPT_ACCEPTED && r.leaves_qty > 0 && mine.size() < 64)
            mine.push_back(r.order_id);
        else if ((r.kind == MKTSIM_RPT_EXECUTION && r.leaves_qty == 0) || r.kind == MKTSIM_RPT_CANCELLED) {
            for (std::size_t i = 0; i < mine.size(); i++)
                if (mine[i] == r.order_id) { mine[i] = mine.back(); mine.pop_back(); break; }
        }
    }

  private:
    Context ctx_;
    std::mt19937_64 rng_;
    std::uniform_real_distribution<double> uni_{0.0, 1.0};
    std::normal_distribution<double> gauss_{0.0, 1.0};
    std::vector<double> mid_;
    double excess_;
    std::uint64_t last_ns_;
    std::vector<std::vector<std::uint64_t>> live_;   // resting order ids per session
};
)CPP";

const char *kFlowAdapter = R"CPP(// {{NAME}}: generated flow adapter. You should not need to edit this file.
// Opens N sessions, paces Model::next() at Model::rate(), submits, polls.
#include "ingress/api.h"
#include "model.hpp"
#include <atomic>
#include <chrono>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <string>
#include <thread>
#include <vector>

namespace {

std::string cfg_str(const std::string &obj, const char *key) {
    std::string k = std::string("\"") + key + "\"";
    std::size_t p = obj.find(k);
    if (p == std::string::npos) return "";
    p = obj.find(':', p + k.size());
    if (p == std::string::npos) return "";
    ++p;
    while (p < obj.size() && (obj[p] == ' ' || obj[p] == '\t')) ++p;
    if (p >= obj.size()) return "";
    if (obj[p] == '"') {
        std::size_t e = obj.find('"', p + 1);
        return e == std::string::npos ? "" : obj.substr(p + 1, e - p - 1);
    }
    std::size_t e = p;
    while (e < obj.size() && (std::isalnum(static_cast<unsigned char>(obj[e])) || obj[e] == '.')) ++e;
    return obj.substr(p, e - p);
}

struct Adapter {
    const mktsim_exchange_api *api;
    mktsim_exchange *ex;
    Context ctx;
    double rate_override = 0;
    std::vector<mktsim_session *> sessions;
    std::unique_ptr<Model> model;
    std::thread thread;
    std::atomic<bool> running{false};
    std::uint64_t submitted = 0, busy = 0;

    static void on_report(void *user, const mktsim_report *r) {
        auto *pair = static_cast<std::pair<Adapter *, int> *>(user);
        pair->first->model->on_report(pair->second, *r);
    }

    void run() {
        using clock = std::chrono::steady_clock;
        double rate = rate_override > 0 ? rate_override : model->rate();
        const double ns_per = rate > 0 ? 1e9 / rate : 1e6;
        auto start = clock::now();
        std::uint64_t slot = 0;
        std::vector<std::pair<Adapter *, int>> users;
        for (int i = 0; i < ctx.sessions; i++) users.emplace_back(this, i);
        while (running.load(std::memory_order_relaxed)) {
            auto now = clock::now();
            std::uint64_t elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(now - start).count();
            std::uint64_t due = static_cast<std::uint64_t>(elapsed / ns_per);
            int n = 0;
            while (slot < due && n < 256 && running.load(std::memory_order_relaxed)) {
                Order o;
                if (model->next(api->now_ns(), o)) {
                    mktsim_order_req req{};
                    req.request_id = ++submitted;
                    req.kind = o.kind; req.side = o.side; req.ord_type = o.ord_type; req.tif = o.tif;
                    req.symbol_id = o.symbol_id; req.qty = o.qty; req.price = o.price; req.order_id = o.order_id;
                    int s = o.session < 0 || o.session >= ctx.sessions ? 0 : o.session;
                    if (api->submit(sessions[s], &req) == MKTSIM_EBUSY) busy++;
                }
                slot++; n++;
            }
            for (int i = 0; i < ctx.sessions; i++)
                api->poll(sessions[i], &Adapter::on_report, &users[i], 1024);
            if (slot >= due)
                std::this_thread::sleep_for(std::chrono::microseconds(50));
        }
    }
};

} // namespace

extern "C" {

int mktsim_ingress_init(const mktsim_exchange_api *api, mktsim_exchange *ex, const char *config_json, void **state) {
    if (api->version != MKTSIM_INGRESS_API_VERSION) return 1;
    auto *a = new Adapter{};
    a->api = api; a->ex = ex;
    std::string cfg = config_json ? config_json : "{}";
    a->ctx.config_json = cfg;
    std::string v;
    a->ctx.sessions = (v = cfg_str(cfg, "sessions")).empty() ? {{SESSIONS}} : std::atoi(v.c_str());
    if (a->ctx.sessions < 1) a->ctx.sessions = 1;
    a->ctx.seed = (v = cfg_str(cfg, "seed")).empty() ? 1 : std::strtoull(v.c_str(), nullptr, 10);
    if (!(v = cfg_str(cfg, "rate")).empty()) a->rate_override = std::atof(v.c_str());
    mktsim_symbol_info syms[4096];
    std::size_t n = api->symbols(ex, syms, 4096);
    a->ctx.symbols.assign(syms, syms + n);
    *state = a;
    return 0;
}

int mktsim_ingress_start(void *state) {
    auto *a = static_cast<Adapter *>(state);
    for (int i = 0; i < a->ctx.sessions; i++)
        a->sessions.push_back(a->api->open_session(a->ex, "{{NAME}}"));
    a->model = std::make_unique<Model>(a->ctx);
    a->running.store(true);
    a->thread = std::thread([a] { a->run(); });
    double rate = a->rate_override > 0 ? a->rate_override : a->model->rate();
    a->api->log(a->ex, "{{NAME}}", (std::to_string(a->ctx.sessions) + " session(s), " +
                                   std::to_string(static_cast<long>(rate)) + " orders/s target, " +
                                   std::to_string(a->ctx.symbols.size()) + " symbols").c_str());
    return 0;
}

void mktsim_ingress_stop(void *state) {
    auto *a = static_cast<Adapter *>(state);
    if (!a->running.exchange(false)) return;
    if (a->thread.joinable()) a->thread.join();
    for (auto *s : a->sessions) a->api->close_session(s);
    a->sessions.clear();
}

void mktsim_ingress_destroy(void *state) { delete static_cast<Adapter *>(state); }

} // extern "C"
)CPP";

const char *kPyGitignore = "__pycache__/\nmktsim/__pycache__/\n";


} // namespace

std::string library_path(const Spec &spec) {
    return (spec.dir / "build" / spec.name).string();
}

std::string generate(const Spec &spec) {
    std::error_code ec;
    if (spec.name.empty())
        return "project name is empty";
    for (char c : spec.name)
        if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_'))
            return "project name must be letters, digits and _ only";
    if (fs::exists(spec.dir / "src" / "protocol.hpp", ec))
        return spec.dir.string() + " already contains a scaffolded adapter";

    fs::path api = spec.repo / "gateway" / "include" / "ingress" / "api.h";
    if (!fs::is_regular_file(api, ec))
        return "cannot find the ingress API header at " + api.string();

    auto sub = [&](const char *tpl) {
        return replace_all(replace_all(tpl, "{{NAME}}", spec.name), "{{PORT}}", std::to_string(spec.port));
    };

    std::string err;
    if (!write_file(spec.dir / "CMakeLists.txt", sub(kCMake), err)) return err;
    if (!write_file(spec.dir / "README.md", sub(kReadme), err)) return err;
    if (!write_file(spec.dir / "src" / "protocol.hpp", sub(kProtocol), err)) return err;
    if (!write_file(spec.dir / "src" / "adapter.cpp", sub(kAdapter), err)) return err;
    if (!write_file(spec.dir / ".gitignore", kGitignore, err)) return err;
    fs::create_directories(spec.dir / "include" / "ingress", ec);
    fs::copy_file(api, spec.dir / "include" / "ingress" / "api.h",
                  fs::copy_options::overwrite_existing, ec);
    if (ec)
        return "cannot copy api.h: " + ec.message();
    return "";
}

static std::string copy_tree(const fs::path &from, const fs::path &to) {
    std::error_code ec;
    fs::create_directories(to, ec);
    for (auto &entry : fs::directory_iterator(from, ec)) {
        if (entry.is_directory()) {
            if (entry.path().filename() == "__pycache__") continue;
            std::string e = copy_tree(entry.path(), to / entry.path().filename());
            if (!e.empty()) return e;
        } else if (entry.path().extension() == ".py") {
            fs::copy_file(entry.path(), to / entry.path().filename(),
                          fs::copy_options::overwrite_existing, ec);
            if (ec) return "cannot copy " + entry.path().string() + ": " + ec.message();
        }
    }
    return "";
}

std::string generate_python(const Spec &spec) {
    std::error_code ec;
    if (spec.name.empty())
        return "project name is empty";
    for (char c : spec.name)
        if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_'))
            return "project name must be letters, digits and _ only";
    const char *main_file = spec.market ? "market.py" : "strategy.py";
    if (fs::exists(spec.dir / main_file, ec))
        return spec.dir.string() + " already contains " + main_file;
    fs::path pkg = spec.repo / "python" / "mktsim";
    if (!fs::is_directory(pkg, ec))
        return "cannot find the Python client at " + pkg.string();

    auto sub = [&](const char *tpl) {
        std::string t = tpl;
        t = replace_all(t, "{{NAME}}", spec.name);
        t = replace_all(t, "{{PORT}}", std::to_string(spec.port));
        t = replace_all(t, "{{MAIN}}", main_file);
        t = replace_all(t, "{{GROUP}}", spec.feed_group);
        t = replace_all(t, "{{FEEDPORT}}", std::to_string(spec.feed_port));
        t = replace_all(t, "{{SNAPPORT}}", std::to_string(spec.snapshot_port));
        // run(..., feed=Feed(...)) for the trader when the feed is not on defaults
        std::string feed = (spec.feed_group == "239.1.1.1" && spec.feed_port == 30001 && spec.snapshot_port == 30003)
                               ? "True"
                               : "Feed(group=\"" + spec.feed_group + "\", port=" + std::to_string(spec.feed_port) +
                                     ", snapshot_port=" + std::to_string(spec.snapshot_port) + ")";
        t = replace_all(t, "{{FEED}}", feed);
        return t;
    };
    std::string err;
    std::string main_src = sub(spec.market ? kPyMarket : kPyStrategy);
    if (!spec.market && main_src.find("Feed(") != std::string::npos)
        main_src = replace_all(main_src, "from mktsim import Report, Strategy, run", "from mktsim import Feed, Report, Strategy, run");
    if (!write_file(spec.dir / main_file, main_src, err)) return err;
    if (!write_file(spec.dir / "README.md", sub(kPyReadme), err)) return err;
    if (!write_file(spec.dir / ".gitignore", kPyGitignore, err)) return err;
    return copy_tree(pkg, spec.dir / "mktsim");
}

std::string generate_flow_model(const Spec &spec) {
    std::error_code ec;
    if (spec.name.empty())
        return "project name is empty";
    for (char c : spec.name)
        if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_'))
            return "project name must be letters, digits and _ only";
    if (fs::exists(spec.dir / "src" / "model.hpp", ec))
        return spec.dir.string() + " already contains a flow model";
    fs::path api = spec.repo / "gateway" / "include" / "ingress" / "api.h";
    if (!fs::is_regular_file(api, ec))
        return "cannot find the ingress API header at " + api.string();
    auto sub = [&](const char *tpl) {
        std::string t = tpl;
        t = replace_all(t, "{{NAME}}", spec.name);
        t = replace_all(t, "{{SESSIONS}}", std::to_string(spec.sessions));
        t = replace_all(t, "{{RATE}}", std::to_string(spec.rate));
        return t;
    };
    std::string err;
    if (!write_file(spec.dir / "CMakeLists.txt", sub(kFlowCMake), err)) return err;
    if (!write_file(spec.dir / "README.md", sub(kFlowReadme), err)) return err;
    if (!write_file(spec.dir / "src" / "model.hpp", sub(kFlowModel), err)) return err;
    if (!write_file(spec.dir / "src" / "flow_adapter.cpp", sub(kFlowAdapter), err)) return err;
    if (!write_file(spec.dir / ".gitignore", kGitignore, err)) return err;
    fs::create_directories(spec.dir / "include" / "ingress", ec);
    fs::copy_file(api, spec.dir / "include" / "ingress" / "api.h", fs::copy_options::overwrite_existing, ec);
    if (ec) return "cannot copy api.h: " + ec.message();
    return "";
}

int build(const Spec &spec) {
    std::string dir = spec.dir.string();
    auto q = [](const std::string &s) { return "'" + s + "'"; };
    std::string cmd = "cmake -S " + q(dir) + " -B " + q(dir + "/build") +
                      " -DCMAKE_BUILD_TYPE=Release >/dev/null && cmake --build " +
                      q(dir + "/build") + " 2>&1 | grep -E 'error|warning|Built target' || true";
    int rc = std::system(cmd.c_str());
    (void)rc;
    // Success is the library existing
    std::error_code ec;
    std::string base = library_path(spec);
    return (fs::exists(base + ".dylib", ec) || fs::exists(base + ".so", ec)) ? 0 : 1;
}

} // namespace scaffold
